### ISSUE TITLE
android support, maybe?

### ISSUE THREAD

**Issue by dawidmosk** [RomanBelkov/XZ.NET#11]
it's possible?

**Comment by RomanBelkov** [comment]
Hi @dawidmosk,

If you are using something like Xamarin – this lib should work.
If you are using Java – try Tukaani XZ for Java, it should be good. May be not so high-level in abstractions, but worth taking a look anyway.

Maybe it's worth coding additional logic on top of XZ for Java, but this would definitely be another project and not XZ.NET.

**Comment by dawidmosk** [comment]
Thank you for quick answer. I'm using xamarin.android as stream and not working fully (problem with loading lzma library). Finally i found something for this platform: TukaaniXZ(java) + Xamarin.Android.Apache.CommonCompress via nuget forc#.
