### ISSUE TITLE
Is MaxThreads limitation necessary?

### ISSUE THREAD

**Issue by goldenbull** [RomanBelkov/XZ.NET#4]
class XZOutputStream has a constant value
`private const int MaxThreads = 8;`
I think the multi-thread config should be decided by user.
For example, I'm going to write some C# app using xz to archive some log files on a server which has 40 cores -- yes, a very powerful server, so I hope to use 32 threads to do the compression in parallel :)
In case when user has set an irrational number of threads, we can use `Trace.TraceWarning` to issue a warning message.

**Comment by RomanBelkov** [comment]
A good idea indeed. I will implement this ASAP (though it would take some time)

**Comment by goldenbull** [comment]
I have created a pull request :)

**Comment by RomanBelkov** [comment]
Accepted #5
