### ISSUE TITLE
XZOutputStream failes if preset is larger than 7 

### ISSUE THREAD

**Issue by ied206** [RomanBelkov/XZ.NET#9]
`XZOutputStream` throws an exception when its preset set to 8 or 9.
For detail, this exception is raised from XZOutputStream.cs line 83.
```
System.InsufficientMemoryException: 'Memory allocation failed'
```

It only happens if XZ.NET is using 32bit version of `liblzma.dll`, and it happens regardless of `liblzma.dll`'s version (5.2.1 and 5.2.3 tested).

To reproduce, please use the test code from pull request #8 .

**Tested Environment**
- Windows 10 x64 v1709
- .Net Framework 4.7.1 installed
- XZ.NET 2.0 trageting .Net Framework 4 Client Profile

**Comment by ied206** [comment]
This error does not happen when argument 'threads' is set to 1 in `XZOutputStream` constructor.

**Comment by pentp** [comment]
The multi-threaded encoder creates separate encoding threads, each with its own memory allocation. With presets 8 or 9 it could easily use many gigabytes of memory, overflowing the 32-bit process address space limits.

I would recommend using a lower preset (faster, slightly lower compression ratio) or less threads (slower), depending on the use case.

**Comment by ied206** [comment]
I missed xz's large memory compression requirement, thanks for explaining.
My test environment has 8 threads which ends up 5392MB with preset 9. 
Alloction about 5GB of memory would be impossible in Windows x86's 2GB userland memory restrict.
